=== massoo/java-playground/target/classes/xml/books.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" type="book" minOccurs="1" maxOccurs="100"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="book">
        <xs:sequence>
            <xs:element name="author" type="author" minOccurs="1" maxOccurs="1" />
            <xs:element name="title" type="title" minOccurs="1" maxOccurs="1"/>
            <xs:element name="price" type="price" minOccurs="1" maxOccurs="1"/>
            <xs:element name="publish_date" type="publish_date" minOccurs="1" maxOccurs="1"/>
            <xs:element name="virtual-library-path" type="virtual-library-path" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:long"/>
    </xs:complexType>

    <xs:simpleType name="author">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9_ -]{1,20}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="virtual-library-path">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9\-_\.\\: ]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="title">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9_ -]{1,50}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="price">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2" />
            <xs:totalDigits value="6" />
            <xs:minInclusive value="0" />
        </xs:restriction>
    </xs:simpleType>

    <!-- 10 character string prevents time zone being included -->
    <xs:simpleType name="publish_date">
        <xs:restriction base="xs:date">
            <xs:minInclusive value="1920-01-01"/>
            <xs:maxInclusive value="2050-12-31"/>
            <xs:pattern value=".{10}"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== massoo/java-playground/src/main/resources/xml/entity-expansion.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE urn:books [
        <!ENTITY lol "lol">
        <!ENTITY lol2 "&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;">
        <!ENTITY lol3 "&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;">
        <!ENTITY lol4 "&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;">
        <!ENTITY lol5 "&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;">
        <!ENTITY lol6 "&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;">
        <!ENTITY lol7 "&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;">
        <!ENTITY lol8 "&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;">
        <!ENTITY lol9 "&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;">
        ]>
<urn:books xmlns:urn="urn:demo.com:books"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="books.xsd" >
  <!--1 to 100 repetitions:-->
  <book id="10">
      <author>&lol9;</author>
      <title>Some title here</title>
      <price>23.00</price>
      <publish_date>1920-01-01</publish_date>
      <virtual-library-path>D:\java.exe</virtual-library-path>
  </book>
    <book id="20">
        <author>Author 2</author>
        <title>Another title here</title>
        <price>30.00</price>
        <publish_date>1990-01-01</publish_date>
        <virtual-library-path>D:\program files\Java\java.exe</virtual-library-path>
    </book>
</urn:books>

=== massoo/java-playground/target/classes/xml/entity-recursion.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE books [
        <!ENTITY companyname "&divisionname; Contoso Inc.">
        <!ENTITY divisionname "&companyname; Web Products Division">
        ]>
<urn:books xmlns:urn="urn:demo.com:books"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="books.xsd" >
  <!--1 to 100 repetitions:-->
  <book id="10">
      <author>&divisionname;</author>
      <title>Some title here</title>
      <price>23.00</price>
      <publish_date>1920-01-01</publish_date>
      <virtual-library-path>D:\java.exe</virtual-library-path>
  </book>
    <book id="20">
        <author>Author 2</author>
        <title>Another title here</title>
        <price>30.00</price>
        <publish_date>1990-01-01</publish_date>
        <virtual-library-path>D:\program files\Java\java.exe</virtual-library-path>
    </book>
</urn:books>

=== massoo/java-playground/src/main/resources/xml/books.xml
<?xml version="1.0" encoding="UTF-8" ?>
<books 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="books.xsd" >
  <book id="10">
    <author>Author 1</author>
    <title>Some title here</title>
    <price>23.00</price>
    <publish_date>1920-01-01</publish_date>
    <virtual-library-path>D:\java.exe</virtual-library-path>
  </book>
    <book id="20">
    <author>Author 2</author>
    <title>Another title here</title>
    <price>30.00</price>
    <publish_date>1990-01-01</publish_date>
    <virtual-library-path>D:\program files\Java\java.exe</virtual-library-path>
  </book>
</books>
